### ISSUE TITLE
Request for darts_dataset_fullytrain.pth.tar

### ISSUE THREAD

**Issue by pprp** [lyq998/CDP#1]
Hi, Thank you for your great job! 

I want to run your code `train_gcn_target.py`, but I can't find the required file `darts_dataset_fullytrain.pth.tar`. 

Would it be possible for you to upload the file to a platform like GitHub, Baidu Netdisk, or Google Cloud? I would greatly appreciate it if you could provide me with access to the file through one of these platforms.

Thank you once again for your assistance. 😄

**Comment by lyq998** [comment]
> Hi, Thank you for your great job!
> 
> I want to run your code `train_gcn_target.py`, but I can't find the required file `darts_dataset_fullytrain.pth.tar`.
> 
> Would it be possible for you to upload the file to a platform like GitHub, Baidu Netdisk, or Google Cloud? I would greatly appreciate it if you could provide me with access to the file through one of these platforms.
> 
> Thank you once again for your assistance. 😄

Thank you for your interest in our work!

This file looks like a test script I wrote early in the experiment and should be deleted.

You can ignore this script as it does not provide the experimental results in the paper.

If you want to know more about gcn experiments, you can refer to https://github.com/lyq998/CDP/blob/main/cross_domain_predictor.py
